void main(List<String> args) {
  try{
    // code that can generate exception

  }catch(Exception){
    print('Error Occured ! \n');
  }
}